---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DevBackendQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: dev-queue-1
      SqsManagedSseEnabled: false
      KmsMasterKeyId: "arn:aws:kms:us-east-1:123456789012:key/1234abcd-1234-abcd-1234-abcd1234abcd",
      KmsDataKeyReusePeriodSeconds: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt 'SQSDeadLetterQueue.Arn'
        maxReceiveCount: 5

